### PR TITLE
Xeno's SAS4 weapons pack sound update + PKs Rebalancing ammo tweaks

### PR DESCRIPTION
**Pull request by CV514**
Done: updated all guns parameters to include actual reload noise and have less absurd firing noise. Previously: some guns as loud as rocket launcher, not counting the innate ammo loudness.

To do next: give all guns sounds based on Otopack files and some definitions on how they should look with tiles. For now it is done for three LMPs as example. PR could be on hold for a few days while I'm on it, but may be safely merged as it is too.

To do in general: little balance here and there, check for missing parameters since those guns are made without copying archetypes from base game.

### CODE REVIEW

**Comment by Kenan2000** [comment]
@CV514 Well, do you want me to merge your current work now or should I wait until you include more updates and commits to this mod as well?

**Comment by CV514** [comment]
> 
> 
> @CV514 Well, do you want me to merge your current work now or should I wait until you include more updates and commits to this mod as well?

As you see fit! I will do the rest of the changes before this week ends, hopefully.

**Comment by CV514** [comment]
I've got sudden free day at home, so all sounds in place and this PR can be merged now. Fire sounds are based on main caliber, reload sounds are based on gun archetype.

Graphics are little more complex - those guns have vivid textual description and somewhere existing graphics can be used, in other places it's completely unique stuff, like the gun inspired by Vita-Saw from TF2; better left if for now and provide this mod it's separate tileset files later.

Another todo: adjust prices and look through volumes/weights.

**Comment by CV514** [comment]
More commits to address https://github.com/Kenan2000/Bright-Nights-Kenan-Mod-Pack/issues/35 

Craft recipes: all of .410 ammo types in reloaded form
Uncraft recipes: all of .410 ammo types and BFG shells - last one is very demanding in skills and equipment.

Changes:
* Removed .410 shot and it's reloaded version since they are defined in the base game files already. Changed spawns and scenarios accordingly. All mod files now using base game casings for that ammo type.
* Tweaks to BFG shells: a little increase in weight and volume to be in line with new uncraft recipe and be meaningful. Change in blast damage - I'm still finding that too low for that particular gun, this may require future reviewing.
* Changed BFG shell material fire resistance to be more fire resistant to be coherent with item description.
* Little changes in spelling and formatting here and there.

Removed ammo is defined in obsolete.json for existing save games compatibility.

**Pull request merged**
